-- CREATE TABLES
CREATE TABLE IF NOT EXISTS brands( id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL );
CREATE TABLE IF NOT EXISTS products( id BIGINT PRIMARY KEY NOT NULL, name VARCHAR(255) NOT NULL );
CREATE TABLE IF NOT EXISTS prices( id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, brand_id BIGINT NOT NULL, start_date TIMESTAMP NOT NULL, end_date TIMESTAMP NOT NULL, price_list INTEGER NOT NULL, product_id BIGINT NOT NULL, priority INTEGER NOT NULL, price DOUBLE PRECISION NOT NULL, curr VARCHAR(10) NOT NULL );

-- FOREIGN KEYS
 ALTER TABLE prices ADD FOREIGN KEY (brand_id)  REFERENCES brands(id);
 ALTER TABLE prices ADD FOREIGN KEY (product_id)  REFERENCES products(id);
